// Auto-generated by scripts/optimize-images.ts
// Do not edit manually. Re-run `npm run optimize-images` to regenerate.

export interface ProductImageAsset {
  productSlug: string;
  viewName: string;
  isMacro: boolean;
  altText: string;
  squareImages: {
    width: number;
    webp: string;
    jpg: string;
    sizeWebp: number;
    sizeJpg: number;
  }[];
  cardImages: {
    width: number;
    webp: string;
    jpg: string;
    sizeWebp: number;
    sizeJpg: number;
  }[];
  blurDataUrl: string;
}

export const PRODUCT_IMAGE_REGISTRY: Record<string, ProductImageAsset[]> = {
  "reversible-formal-casual-belt": [
    {
      "productSlug": "reversible-formal-casual-belt",
      "viewName": "hero",
      "isMacro": false,
      "altText": "Dino Leathers Executive Ratchet Belt with brushed silver buckle in Jet Black coiled on travertine pedestal",
      "squareImages": [
        {
          "width": 480,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-1x1-480.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-1x1-480.jpg",
          "sizeWebp": 28694,
          "sizeJpg": 32069
        },
        {
          "width": 960,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-1x1-960.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-1x1-960.jpg",
          "sizeWebp": 79440,
          "sizeJpg": 99505
        },
        {
          "width": 1600,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-1x1-1600.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-1x1-1600.jpg",
          "sizeWebp": 144602,
          "sizeJpg": 213346
        }
      ],
      "cardImages": [
        {
          "width": 480,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-4x5-480.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-4x5-480.jpg",
          "sizeWebp": 31802,
          "sizeJpg": 37222
        },
        {
          "width": 960,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-4x5-960.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-4x5-960.jpg",
          "sizeWebp": 85840,
          "sizeJpg": 113132
        },
        {
          "width": 1600,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-4x5-1600.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-4x5-1600.jpg",
          "sizeWebp": 159134,
          "sizeJpg": 240887
        }
      ],
      "blurDataUrl": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAQCdASoQABAABIByJZACdADXCIg4GAAA/phA2JA6OiZPh21NyrHLVV232JI6fEPZvylEw8VxM1++qEJzDskjyW0Mzq/Vh2QXsoN59jjPd3RRO9+P0B/e1E/UnnGGRlYWBZ6gAAA="
    },
    {
      "productSlug": "reversible-formal-casual-belt",
      "viewName": "angle-lifestyle",
      "isMacro": false,
      "altText": "Dino Leathers Executive Belt in rich Ambur Cognac Tan leather variation coiled on stone pedestal",
      "squareImages": [
        {
          "width": 480,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-1x1-480.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-1x1-480.jpg",
          "sizeWebp": 30246,
          "sizeJpg": 33720
        },
        {
          "width": 960,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-1x1-960.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-1x1-960.jpg",
          "sizeWebp": 86072,
          "sizeJpg": 106990
        },
        {
          "width": 1600,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-1x1-1600.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-1x1-1600.jpg",
          "sizeWebp": 158762,
          "sizeJpg": 229727
        }
      ],
      "cardImages": [
        {
          "width": 480,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-4x5-480.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-4x5-480.jpg",
          "sizeWebp": 34596,
          "sizeJpg": 39365
        },
        {
          "width": 960,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-4x5-960.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-4x5-960.jpg",
          "sizeWebp": 95052,
          "sizeJpg": 121490
        },
        {
          "width": 1600,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-4x5-1600.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-4x5-1600.jpg",
          "sizeWebp": 173466,
          "sizeJpg": 260940
        }
      ],
      "blurDataUrl": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADwAQCdASoQABAABIByJbACdADNDhUPwsgA/pgNZIKzrcU9F7HNGit9s/AUUY4Japw3edKeGjv1KfL4AONupWJu1mtK3/dXLz9o+uEKGFEaCYPN4Ywc39QE1N7lopFFXq9GZwAA"
    },
    {
      "productSlug": "reversible-formal-casual-belt",
      "viewName": "hardware-mechanism",
      "isMacro": false,
      "altText": "Close-up of innovative 32-notch micro-ratchet track mechanism and automatic quick-release lever",
      "squareImages": [
        {
          "width": 480,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-1x1-480.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-1x1-480.jpg",
          "sizeWebp": 39858,
          "sizeJpg": 41895
        },
        {
          "width": 960,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-1x1-960.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-1x1-960.jpg",
          "sizeWebp": 116548,
          "sizeJpg": 131276
        },
        {
          "width": 1600,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-1x1-1600.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-1x1-1600.jpg",
          "sizeWebp": 202178,
          "sizeJpg": 270851
        }
      ],
      "cardImages": [
        {
          "width": 480,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-4x5-480.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-4x5-480.jpg",
          "sizeWebp": 47190,
          "sizeJpg": 50064
        },
        {
          "width": 960,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-4x5-960.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-4x5-960.jpg",
          "sizeWebp": 121538,
          "sizeJpg": 148883
        },
        {
          "width": 1600,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-4x5-1600.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-4x5-1600.jpg",
          "sizeWebp": 217984,
          "sizeJpg": 306491
        }
      ],
      "blurDataUrl": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQAQCdASoQABAABIByJZACdADP35KgAAD9/KeNqCnCTSLEeUaN0E/BB58etCwyPGbMXD3ta8gHx/hVp5+JO6xpWWPrNA/l+YoAHDBQFVwcZ7fKesJW/17PGwqAbLG0UHyfpdYUgAA="
    },
    {
      "productSlug": "reversible-formal-casual-belt",
      "viewName": "giftbox-display",
      "isMacro": false,
      "altText": "Handcrafted matte black and walnut gift box unboxing display with certificate of authenticity",
      "squareImages": [
        {
          "width": 480,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-giftbox-display-1x1-480.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-giftbox-display-1x1-480.jpg",
          "sizeWebp": 41802,
          "sizeJpg": 43606
        },
        {
          "width": 960,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-giftbox-display-1x1-960.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-giftbox-display-1x1-960.jpg",
          "sizeWebp": 116928,
          "sizeJpg": 138941
        },
        {
          "width": 1600,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-giftbox-display-1x1-1600.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-giftbox-display-1x1-1600.jpg",
          "sizeWebp": 205720,
          "sizeJpg": 286212
        }
      ],
      "cardImages": [
        {
          "width": 480,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-giftbox-display-4x5-480.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-giftbox-display-4x5-480.jpg",
          "sizeWebp": 46988,
          "sizeJpg": 50937
        },
        {
          "width": 960,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-giftbox-display-4x5-960.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-giftbox-display-4x5-960.jpg",
          "sizeWebp": 116198,
          "sizeJpg": 150690
        },
        {
          "width": 1600,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-giftbox-display-4x5-1600.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-giftbox-display-4x5-1600.jpg",
          "sizeWebp": 211838,
          "sizeJpg": 311477
        }
      ],
      "blurDataUrl": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADwAQCdASoQABAABIByJZgCdAC9wRXrrAAA/pPR+jq5V8GC/bFWarEmVHexUbHg40jtUnAXylgbUPy/ouY/MAjnNBGTF+TEVV4SUstAKfHTbZgZnLgsIp+fyPy9MtVpdsrlbQsPj3UzPLBywO2E+AAA"
    },
    {
      "productSlug": "reversible-formal-casual-belt",
      "viewName": "worn-lifestyle",
      "isMacro": false,
      "altText": "Dino Leathers belt styled on formal tailored trousers and crisp collared shirt",
      "squareImages": [
        {
          "width": 480,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-1x1-480.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-1x1-480.jpg",
          "sizeWebp": 21900,
          "sizeJpg": 28281
        },
        {
          "width": 960,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-1x1-960.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-1x1-960.jpg",
          "sizeWebp": 63816,
          "sizeJpg": 88067
        },
        {
          "width": 1600,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-1x1-1600.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-1x1-1600.jpg",
          "sizeWebp": 127942,
          "sizeJpg": 196606
        }
      ],
      "cardImages": [
        {
          "width": 480,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-4x5-480.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-4x5-480.jpg",
          "sizeWebp": 24450,
          "sizeJpg": 32611
        },
        {
          "width": 960,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-4x5-960.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-4x5-960.jpg",
          "sizeWebp": 73906,
          "sizeJpg": 103010
        },
        {
          "width": 1600,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-4x5-1600.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-4x5-1600.jpg",
          "sizeWebp": 148114,
          "sizeJpg": 231448
        }
      ],
      "blurDataUrl": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoQABAABIByJYwAAhY8+rO1AAD+188Po6EqXo3ilOXqI6yu+qsloyOEBYek08/hCu2RwBUNVdg0ZeG7jAPrQU/1hJkbfpiVO+DHkivKtvKPIAAA"
    },
    {
      "productSlug": "reversible-formal-casual-belt",
      "viewName": "macro-grain",
      "isMacro": true,
      "altText": "High-definition macro texture of brushed steel buckle and full-grain Ambur bovine leather",
      "squareImages": [
        {
          "width": 480,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-1x1-480.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-1x1-480.jpg",
          "sizeWebp": 34580,
          "sizeJpg": 35913
        },
        {
          "width": 960,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-1x1-960.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-1x1-960.jpg",
          "sizeWebp": 104462,
          "sizeJpg": 115415
        },
        {
          "width": 1600,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-1x1-1600.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-1x1-1600.jpg",
          "sizeWebp": 184188,
          "sizeJpg": 240984
        }
      ],
      "cardImages": [
        {
          "width": 480,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-4x5-480.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-4x5-480.jpg",
          "sizeWebp": 43020,
          "sizeJpg": 43676
        },
        {
          "width": 960,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-4x5-960.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-4x5-960.jpg",
          "sizeWebp": 115164,
          "sizeJpg": 133658
        },
        {
          "width": 1600,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-4x5-1600.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-4x5-1600.jpg",
          "sizeWebp": 205642,
          "sizeJpg": 279224
        }
      ],
      "blurDataUrl": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQAgCdASoQABAABIByJQBOgBmEpGmhN2+AAP5kubzqUVWP3h8wUDEGI6dB45QHzNUyzAY4f3DUIJIgAQyTJQ+SYVoQ60MX0qE+cyAJMIrm9czcn40FQF3g84nSE4z3XeOTgAAA"
    }
  ],
};

export function getProductGalleryAssets(slug: string): ProductImageAsset[] {
  return PRODUCT_IMAGE_REGISTRY[slug] || [];
}