// Auto-generated by scripts/optimize-images.ts
// Do not edit manually. Re-run `npm run optimize-images` to regenerate.

export interface ProductImageAsset {
  productSlug: string;
  viewName: string;
  isMacro: boolean;
  altText: string;
  squareImages: {
    width: number;
    webp: string;
    jpg: string;
    sizeWebp: number;
    sizeJpg: number;
  }[];
  cardImages: {
    width: number;
    webp: string;
    jpg: string;
    sizeWebp: number;
    sizeJpg: number;
  }[];
  blurDataUrl: string;
}

export const PRODUCT_IMAGE_REGISTRY: Record<string, ProductImageAsset[]> = {
  "reversible-formal-casual-belt": [
    {
      "productSlug": "reversible-formal-casual-belt",
      "viewName": "hero",
      "isMacro": false,
      "altText": "Dino Leathers Executive Ratchet Belt with brushed silver buckle in Jet Black coiled on travertine pedestal",
      "squareImages": [
        {
          "width": 480,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-1x1-480.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-1x1-480.jpg",
          "sizeWebp": 28694,
          "sizeJpg": 32069
        },
        {
          "width": 960,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-1x1-960.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-1x1-960.jpg",
          "sizeWebp": 79440,
          "sizeJpg": 99505
        },
        {
          "width": 1600,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-1x1-1600.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-1x1-1600.jpg",
          "sizeWebp": 144602,
          "sizeJpg": 213346
        }
      ],
      "cardImages": [
        {
          "width": 480,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-4x5-480.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-4x5-480.jpg",
          "sizeWebp": 31802,
          "sizeJpg": 37222
        },
        {
          "width": 960,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-4x5-960.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-4x5-960.jpg",
          "sizeWebp": 85840,
          "sizeJpg": 113132
        },
        {
          "width": 1600,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-4x5-1600.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-4x5-1600.jpg",
          "sizeWebp": 159134,
          "sizeJpg": 240887
        }
      ],
      "blurDataUrl": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAQCdASoQABAABIByJZACdADXCIg4GAAA/phA2JA6OiZPh21NyrHLVV232JI6fEPZvylEw8VxM1++qEJzDskjyW0Mzq/Vh2QXsoN59jjPd3RRO9+P0B/e1E/UnnGGRlYWBZ6gAAA="
    },
    {
      "productSlug": "reversible-formal-casual-belt",
      "viewName": "angle-lifestyle",
      "isMacro": false,
      "altText": "Dino Leathers Executive Belt in rich Ambur Cognac Tan leather variation coiled on stone pedestal",
      "squareImages": [
        {
          "width": 480,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-1x1-480.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-1x1-480.jpg",
          "sizeWebp": 30246,
          "sizeJpg": 33720
        },
        {
          "width": 960,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-1x1-960.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-1x1-960.jpg",
          "sizeWebp": 86072,
          "sizeJpg": 106990
        },
        {
          "width": 1600,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-1x1-1600.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-1x1-1600.jpg",
          "sizeWebp": 158762,
          "sizeJpg": 229727
        }
      ],
      "cardImages": [
        {
          "width": 480,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-4x5-480.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-4x5-480.jpg",
          "sizeWebp": 34596,
          "sizeJpg": 39365
        },
        {
          "width": 960,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-4x5-960.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-4x5-960.jpg",
          "sizeWebp": 95052,
          "sizeJpg": 121490
        },
        {
          "width": 1600,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-4x5-1600.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-4x5-1600.jpg",
          "sizeWebp": 173466,
          "sizeJpg": 260940
        }
      ],
      "blurDataUrl": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADwAQCdASoQABAABIByJbACdADNDhUPwsgA/pgNZIKzrcU9F7HNGit9s/AUUY4Japw3edKeGjv1KfL4AONupWJu1mtK3/dXLz9o+uEKGFEaCYPN4Ywc39QE1N7lopFFXq9GZwAA"
    },
    {
      "productSlug": "reversible-formal-casual-belt",
      "viewName": "hardware-mechanism",
      "isMacro": false,
      "altText": "Close-up of innovative 32-notch micro-ratchet track mechanism and automatic quick-release lever",
      "squareImages": [
        {
          "width": 480,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-1x1-480.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-1x1-480.jpg",
          "sizeWebp": 39858,
          "sizeJpg": 41895
        },
        {
          "width": 960,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-1x1-960.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-1x1-960.jpg",
          "sizeWebp": 116548,
          "sizeJpg": 131276
        },
        {
          "width": 1600,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-1x1-1600.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-1x1-1600.jpg",
          "sizeWebp": 202178,
          "sizeJpg": 270851
        }
      ],
      "cardImages": [
        {
          "width": 480,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-4x5-480.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-4x5-480.jpg",
          "sizeWebp": 47190,
          "sizeJpg": 50064
        },
        {
          "width": 960,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-4x5-960.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-4x5-960.jpg",
          "sizeWebp": 121538,
          "sizeJpg": 148883
        },
        {
          "width": 1600,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-4x5-1600.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-4x5-1600.jpg",
          "sizeWebp": 217984,
          "sizeJpg": 306491
        }
      ],
      "blurDataUrl": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQAQCdASoQABAABIByJZACdADP35KgAAD9/KeNqCnCTSLEeUaN0E/BB58etCwyPGbMXD3ta8gHx/hVp5+JO6xpWWPrNA/l+YoAHDBQFVwcZ7fKesJW/17PGwqAbLG0UHyfpdYUgAA="
    },
    {
      "productSlug": "reversible-formal-casual-belt",
      "viewName": "giftbox-display",
      "isMacro": false,
      "altText": "Handcrafted matte black and walnut gift box unboxing display with certificate of authenticity",
      "squareImages": [
        {
          "width": 480,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-giftbox-display-1x1-480.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-giftbox-display-1x1-480.jpg",
          "sizeWebp": 41802,
          "sizeJpg": 43606
        },
        {
          "width": 960,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-giftbox-display-1x1-960.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-giftbox-display-1x1-960.jpg",
          "sizeWebp": 116928,
          "sizeJpg": 138941
        },
        {
          "width": 1600,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-giftbox-display-1x1-1600.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-giftbox-display-1x1-1600.jpg",
          "sizeWebp": 205720,
          "sizeJpg": 286212
        }
      ],
      "cardImages": [
        {
          "width": 480,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-giftbox-display-4x5-480.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-giftbox-display-4x5-480.jpg",
          "sizeWebp": 46988,
          "sizeJpg": 50937
        },
        {
          "width": 960,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-giftbox-display-4x5-960.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-giftbox-display-4x5-960.jpg",
          "sizeWebp": 116198,
          "sizeJpg": 150690
        },
        {
          "width": 1600,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-giftbox-display-4x5-1600.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-giftbox-display-4x5-1600.jpg",
          "sizeWebp": 211838,
          "sizeJpg": 311477
        }
      ],
      "blurDataUrl": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADwAQCdASoQABAABIByJZgCdAC9wRXrrAAA/pPR+jq5V8GC/bFWarEmVHexUbHg40jtUnAXylgbUPy/ouY/MAjnNBGTF+TEVV4SUstAKfHTbZgZnLgsIp+fyPy9MtVpdsrlbQsPj3UzPLBywO2E+AAA"
    },
    {
      "productSlug": "reversible-formal-casual-belt",
      "viewName": "worn-lifestyle",
      "isMacro": false,
      "altText": "Dino Leathers belt styled on formal tailored trousers and crisp collared shirt",
      "squareImages": [
        {
          "width": 480,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-1x1-480.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-1x1-480.jpg",
          "sizeWebp": 21900,
          "sizeJpg": 28281
        },
        {
          "width": 960,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-1x1-960.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-1x1-960.jpg",
          "sizeWebp": 63816,
          "sizeJpg": 88067
        },
        {
          "width": 1600,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-1x1-1600.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-1x1-1600.jpg",
          "sizeWebp": 127942,
          "sizeJpg": 196606
        }
      ],
      "cardImages": [
        {
          "width": 480,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-4x5-480.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-4x5-480.jpg",
          "sizeWebp": 24450,
          "sizeJpg": 32611
        },
        {
          "width": 960,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-4x5-960.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-4x5-960.jpg",
          "sizeWebp": 73906,
          "sizeJpg": 103010
        },
        {
          "width": 1600,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-4x5-1600.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-4x5-1600.jpg",
          "sizeWebp": 148114,
          "sizeJpg": 231448
        }
      ],
      "blurDataUrl": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoQABAABIByJYwAAhY8+rO1AAD+188Po6EqXo3ilOXqI6yu+qsloyOEBYek08/hCu2RwBUNVdg0ZeG7jAPrQU/1hJkbfpiVO+DHkivKtvKPIAAA"
    },
    {
      "productSlug": "reversible-formal-casual-belt",
      "viewName": "macro-grain",
      "isMacro": true,
      "altText": "High-definition macro texture of brushed steel buckle and full-grain Ambur bovine leather",
      "squareImages": [
        {
          "width": 480,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-1x1-480.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-1x1-480.jpg",
          "sizeWebp": 34580,
          "sizeJpg": 35913
        },
        {
          "width": 960,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-1x1-960.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-1x1-960.jpg",
          "sizeWebp": 104462,
          "sizeJpg": 115415
        },
        {
          "width": 1600,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-1x1-1600.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-1x1-1600.jpg",
          "sizeWebp": 184188,
          "sizeJpg": 240984
        }
      ],
      "cardImages": [
        {
          "width": 480,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-4x5-480.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-4x5-480.jpg",
          "sizeWebp": 43020,
          "sizeJpg": 43676
        },
        {
          "width": 960,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-4x5-960.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-4x5-960.jpg",
          "sizeWebp": 115164,
          "sizeJpg": 133658
        },
        {
          "width": 1600,
          "webp": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-4x5-1600.webp",
          "jpg": "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-4x5-1600.jpg",
          "sizeWebp": 205642,
          "sizeJpg": 279224
        }
      ],
      "blurDataUrl": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQAgCdASoQABAABIByJQBOgBmEpGmhN2+AAP5kubzqUVWP3h8wUDEGI6dB45QHzNUyzAY4f3DUIJIgAQyTJQ+SYVoQ60MX0qE+cyAJMIrm9czcn40FQF3g84nSE4z3XeOTgAAA"
    }
  ],
  "classic-bifold-coin-wallet": [
    {
      "productSlug": "classic-bifold-coin-wallet",
      "viewName": "hero",
      "isMacro": false,
      "altText": "Dino Leathers Classic Bi-Fold Coin Wallet in handcrafted Ambur Tan and Espresso Black",
      "squareImages": [
        {
          "width": 480,
          "webp": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-hero-1x1-480.webp",
          "jpg": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-hero-1x1-480.jpg",
          "sizeWebp": 33486,
          "sizeJpg": 33487
        },
        {
          "width": 960,
          "webp": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-hero-1x1-960.webp",
          "jpg": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-hero-1x1-960.jpg",
          "sizeWebp": 97740,
          "sizeJpg": 113534
        },
        {
          "width": 1600,
          "webp": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-hero-1x1-1600.webp",
          "jpg": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-hero-1x1-1600.jpg",
          "sizeWebp": 173774,
          "sizeJpg": 234950
        }
      ],
      "cardImages": [
        {
          "width": 480,
          "webp": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-hero-4x5-480.webp",
          "jpg": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-hero-4x5-480.jpg",
          "sizeWebp": 44204,
          "sizeJpg": 43184
        },
        {
          "width": 960,
          "webp": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-hero-4x5-960.webp",
          "jpg": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-hero-4x5-960.jpg",
          "sizeWebp": 111504,
          "sizeJpg": 132687
        },
        {
          "width": 1600,
          "webp": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-hero-4x5-1600.webp",
          "jpg": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-hero-4x5-1600.jpg",
          "sizeWebp": 193008,
          "sizeJpg": 265509
        }
      ],
      "blurDataUrl": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAQCdASoQABAABIByJYgAAuQbfjnAAP6muz0/3hNSJjMeZuLCntUUSXfGWguxf5DyDtCcaBhHN2vYi4binfwAAAA="
    },
    {
      "productSlug": "classic-bifold-coin-wallet",
      "viewName": "tan-display",
      "isMacro": false,
      "altText": "Ambur Tan Full-Grain Bovine Bi-Fold Wallet seated in handcrafted wooden presentation box",
      "squareImages": [
        {
          "width": 480,
          "webp": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-tan-display-1x1-480.webp",
          "jpg": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-tan-display-1x1-480.jpg",
          "sizeWebp": 23566,
          "sizeJpg": 28256
        },
        {
          "width": 960,
          "webp": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-tan-display-1x1-960.webp",
          "jpg": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-tan-display-1x1-960.jpg",
          "sizeWebp": 55610,
          "sizeJpg": 81632
        },
        {
          "width": 1600,
          "webp": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-tan-display-1x1-1600.webp",
          "jpg": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-tan-display-1x1-1600.jpg",
          "sizeWebp": 100832,
          "sizeJpg": 162607
        }
      ],
      "cardImages": [
        {
          "width": 480,
          "webp": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-tan-display-4x5-480.webp",
          "jpg": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-tan-display-4x5-480.jpg",
          "sizeWebp": 27500,
          "sizeJpg": 34473
        },
        {
          "width": 960,
          "webp": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-tan-display-4x5-960.webp",
          "jpg": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-tan-display-4x5-960.jpg",
          "sizeWebp": 62544,
          "sizeJpg": 93864
        },
        {
          "width": 1600,
          "webp": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-tan-display-4x5-1600.webp",
          "jpg": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-tan-display-4x5-1600.jpg",
          "sizeWebp": 112396,
          "sizeJpg": 185544
        }
      ],
      "blurDataUrl": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQABAABIByJYgCdADwr2cxPRAA/nL4wZ8r/eJU0v+tBPNjJygjGaBaiqGw56QkOMczjzEOYKBvgJMxb8AAAA=="
    },
    {
      "productSlug": "classic-bifold-coin-wallet",
      "viewName": "interior-passcase",
      "isMacro": false,
      "altText": "Interior layout of Bi-Fold Wallet showing vertical passcase card flap and currency lining",
      "squareImages": [
        {
          "width": 480,
          "webp": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-interior-passcase-1x1-480.webp",
          "jpg": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-interior-passcase-1x1-480.jpg",
          "sizeWebp": 25476,
          "sizeJpg": 30974
        },
        {
          "width": 960,
          "webp": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-interior-passcase-1x1-960.webp",
          "jpg": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-interior-passcase-1x1-960.jpg",
          "sizeWebp": 63092,
          "sizeJpg": 90856
        },
        {
          "width": 1600,
          "webp": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-interior-passcase-1x1-1600.webp",
          "jpg": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-interior-passcase-1x1-1600.jpg",
          "sizeWebp": 114378,
          "sizeJpg": 183443
        }
      ],
      "cardImages": [
        {
          "width": 480,
          "webp": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-interior-passcase-4x5-480.webp",
          "jpg": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-interior-passcase-4x5-480.jpg",
          "sizeWebp": 31728,
          "sizeJpg": 39258
        },
        {
          "width": 960,
          "webp": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-interior-passcase-4x5-960.webp",
          "jpg": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-interior-passcase-4x5-960.jpg",
          "sizeWebp": 72714,
          "sizeJpg": 107243
        },
        {
          "width": 1600,
          "webp": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-interior-passcase-4x5-1600.webp",
          "jpg": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-interior-passcase-4x5-1600.jpg",
          "sizeWebp": 129820,
          "sizeJpg": 217074
        }
      ],
      "blurDataUrl": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAQCdASoQABAABIByJbACdADDCvHuYAD+m+kXtx6tJWrBTvzbkFmAwkjOAJpSDtQIMRwu1l+CNitrv7GRSEh0NPi/Mr4IQ3LjYsU4HkO78v3IAAA="
    },
    {
      "productSlug": "classic-bifold-coin-wallet",
      "viewName": "macro-grain",
      "isMacro": true,
      "altText": "Macro shot of natural uncorrected grain pores and reinforced bonded saddle-stitching",
      "squareImages": [
        {
          "width": 480,
          "webp": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-macro-grain-1x1-480.webp",
          "jpg": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-macro-grain-1x1-480.jpg",
          "sizeWebp": 19348,
          "sizeJpg": 24610
        },
        {
          "width": 960,
          "webp": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-macro-grain-1x1-960.webp",
          "jpg": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-macro-grain-1x1-960.jpg",
          "sizeWebp": 40970,
          "sizeJpg": 58166
        },
        {
          "width": 1600,
          "webp": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-macro-grain-1x1-1600.webp",
          "jpg": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-macro-grain-1x1-1600.jpg",
          "sizeWebp": 76330,
          "sizeJpg": 121820
        }
      ],
      "cardImages": [
        {
          "width": 480,
          "webp": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-macro-grain-4x5-480.webp",
          "jpg": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-macro-grain-4x5-480.jpg",
          "sizeWebp": 19328,
          "sizeJpg": 26141
        },
        {
          "width": 960,
          "webp": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-macro-grain-4x5-960.webp",
          "jpg": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-macro-grain-4x5-960.jpg",
          "sizeWebp": 43606,
          "sizeJpg": 66980
        },
        {
          "width": 1600,
          "webp": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-macro-grain-4x5-1600.webp",
          "jpg": "/images/products/classic-bifold-coin-wallet/classic-bifold-coin-wallet-macro-grain-4x5-1600.jpg",
          "sizeWebp": 80798,
          "sizeJpg": 133688
        }
      ],
      "blurDataUrl": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoQABAABIByJbACdADIug3VGAD+uCoWXsUe2zzZBMB1mjafBAhFNUylsEL/EndskzJuxTlongAAAA=="
    }
  ],
  "minimalist-slim-rfid-cardholder": [
    {
      "productSlug": "minimalist-slim-rfid-cardholder",
      "viewName": "hero",
      "isMacro": false,
      "altText": "Dino Leathers Minimalist Slim RFID Cardholder with quick-draw card sleeves in Tan and Black",
      "squareImages": [
        {
          "width": 480,
          "webp": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-hero-1x1-480.webp",
          "jpg": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-hero-1x1-480.jpg",
          "sizeWebp": 12128,
          "sizeJpg": 18683
        },
        {
          "width": 960,
          "webp": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-hero-1x1-960.webp",
          "jpg": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-hero-1x1-960.jpg",
          "sizeWebp": 34576,
          "sizeJpg": 59242
        },
        {
          "width": 1600,
          "webp": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-hero-1x1-1600.webp",
          "jpg": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-hero-1x1-1600.jpg",
          "sizeWebp": 68166,
          "sizeJpg": 122847
        }
      ],
      "cardImages": [
        {
          "width": 480,
          "webp": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-hero-4x5-480.webp",
          "jpg": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-hero-4x5-480.jpg",
          "sizeWebp": 14164,
          "sizeJpg": 22263
        },
        {
          "width": 960,
          "webp": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-hero-4x5-960.webp",
          "jpg": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-hero-4x5-960.jpg",
          "sizeWebp": 38610,
          "sizeJpg": 67000
        },
        {
          "width": 1600,
          "webp": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-hero-4x5-1600.webp",
          "jpg": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-hero-4x5-1600.jpg",
          "sizeWebp": 74968,
          "sizeJpg": 136720
        }
      ],
      "blurDataUrl": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQABAABIByJaAC7AEVShHqyHAA/DOqlvhsVfzwU6BeYrC4Twbz18mNAAiGge86vKhg5F119n2q9miaYsIyouLDlijfDkI2CDQoAAAA"
    },
    {
      "productSlug": "minimalist-slim-rfid-cardholder",
      "viewName": "tan-sleeve",
      "isMacro": false,
      "altText": "Crazy Horse Tan Slim RFID Cardholder showing horizontal precision-cut card slots",
      "squareImages": [
        {
          "width": 480,
          "webp": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-tan-sleeve-1x1-480.webp",
          "jpg": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-tan-sleeve-1x1-480.jpg",
          "sizeWebp": 11396,
          "sizeJpg": 17559
        },
        {
          "width": 960,
          "webp": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-tan-sleeve-1x1-960.webp",
          "jpg": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-tan-sleeve-1x1-960.jpg",
          "sizeWebp": 28584,
          "sizeJpg": 47825
        },
        {
          "width": 1600,
          "webp": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-tan-sleeve-1x1-1600.webp",
          "jpg": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-tan-sleeve-1x1-1600.jpg",
          "sizeWebp": 52078,
          "sizeJpg": 92940
        }
      ],
      "cardImages": [
        {
          "width": 480,
          "webp": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-tan-sleeve-4x5-480.webp",
          "jpg": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-tan-sleeve-4x5-480.jpg",
          "sizeWebp": 12938,
          "sizeJpg": 20659
        },
        {
          "width": 960,
          "webp": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-tan-sleeve-4x5-960.webp",
          "jpg": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-tan-sleeve-4x5-960.jpg",
          "sizeWebp": 31584,
          "sizeJpg": 53339
        },
        {
          "width": 1600,
          "webp": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-tan-sleeve-4x5-1600.webp",
          "jpg": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-tan-sleeve-4x5-1600.jpg",
          "sizeWebp": 59266,
          "sizeJpg": 108661
        }
      ],
      "blurDataUrl": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoQABAABIByJbACdAEO/MbvnwAA/tJHJoozw49lFWdu6ave3QOgzP2RqDRmDt4aY/BFqAAA"
    },
    {
      "productSlug": "minimalist-slim-rfid-cardholder",
      "viewName": "black-interior",
      "isMacro": false,
      "altText": "Deep Espresso Black Slim RFID Cardholder with multi-slot card arrangement",
      "squareImages": [
        {
          "width": 480,
          "webp": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-black-interior-1x1-480.webp",
          "jpg": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-black-interior-1x1-480.jpg",
          "sizeWebp": 6992,
          "sizeJpg": 12952
        },
        {
          "width": 960,
          "webp": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-black-interior-1x1-960.webp",
          "jpg": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-black-interior-1x1-960.jpg",
          "sizeWebp": 17442,
          "sizeJpg": 34551
        },
        {
          "width": 1600,
          "webp": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-black-interior-1x1-1600.webp",
          "jpg": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-black-interior-1x1-1600.jpg",
          "sizeWebp": 33824,
          "sizeJpg": 69898
        }
      ],
      "cardImages": [
        {
          "width": 480,
          "webp": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-black-interior-4x5-480.webp",
          "jpg": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-black-interior-4x5-480.jpg",
          "sizeWebp": 7422,
          "sizeJpg": 14256
        },
        {
          "width": 960,
          "webp": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-black-interior-4x5-960.webp",
          "jpg": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-black-interior-4x5-960.jpg",
          "sizeWebp": 18560,
          "sizeJpg": 37289
        },
        {
          "width": 1600,
          "webp": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-black-interior-4x5-1600.webp",
          "jpg": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-black-interior-4x5-1600.jpg",
          "sizeWebp": 35732,
          "sizeJpg": 75431
        }
      ],
      "blurDataUrl": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoQABAABIByJaQAAq4AkGfkAAD+3yYb6MpgWpeJaYVZzZCpAynrhJhlLeAWbCp0y2JYAA=="
    },
    {
      "productSlug": "minimalist-slim-rfid-cardholder",
      "viewName": "macro-grain",
      "isMacro": true,
      "altText": "Macro close-up of wax-infused Crazy Horse bovine leather grain and hand-burnished edges",
      "squareImages": [
        {
          "width": 480,
          "webp": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-macro-grain-1x1-480.webp",
          "jpg": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-macro-grain-1x1-480.jpg",
          "sizeWebp": 14708,
          "sizeJpg": 20440
        },
        {
          "width": 960,
          "webp": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-macro-grain-1x1-960.webp",
          "jpg": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-macro-grain-1x1-960.jpg",
          "sizeWebp": 33182,
          "sizeJpg": 52036
        },
        {
          "width": 1600,
          "webp": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-macro-grain-1x1-1600.webp",
          "jpg": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-macro-grain-1x1-1600.jpg",
          "sizeWebp": 62230,
          "sizeJpg": 105339
        }
      ],
      "cardImages": [
        {
          "width": 480,
          "webp": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-macro-grain-4x5-480.webp",
          "jpg": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-macro-grain-4x5-480.jpg",
          "sizeWebp": 13994,
          "sizeJpg": 21782
        },
        {
          "width": 960,
          "webp": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-macro-grain-4x5-960.webp",
          "jpg": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-macro-grain-4x5-960.jpg",
          "sizeWebp": 32210,
          "sizeJpg": 54762
        },
        {
          "width": 1600,
          "webp": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-macro-grain-4x5-1600.webp",
          "jpg": "/images/products/minimalist-slim-rfid-cardholder/minimalist-slim-rfid-cardholder-macro-grain-4x5-1600.jpg",
          "sizeWebp": 59200,
          "sizeJpg": 108329
        }
      ],
      "blurDataUrl": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoQABAABIByJagC7ADdIvTHSAAA/tlfHRF1H8+JSr3NO7tAKJE92jFIN8iCHO3vdF1pR1nZFo4AAA=="
    }
  ],
  "ambur-heritage-2in1-gift-box": [
    {
      "productSlug": "ambur-heritage-2in1-gift-box",
      "viewName": "hero",
      "isMacro": false,
      "altText": "Ambur Heritage 2-in-1 Executive Gift Set in rigid wooden keepsake packaging boxes",
      "squareImages": [
        {
          "width": 480,
          "webp": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-hero-1x1-480.webp",
          "jpg": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-hero-1x1-480.jpg",
          "sizeWebp": 28530,
          "sizeJpg": 32913
        },
        {
          "width": 960,
          "webp": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-hero-1x1-960.webp",
          "jpg": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-hero-1x1-960.jpg",
          "sizeWebp": 75870,
          "sizeJpg": 105302
        },
        {
          "width": 1600,
          "webp": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-hero-1x1-1600.webp",
          "jpg": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-hero-1x1-1600.jpg",
          "sizeWebp": 140272,
          "sizeJpg": 213986
        }
      ],
      "cardImages": [
        {
          "width": 480,
          "webp": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-hero-4x5-480.webp",
          "jpg": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-hero-4x5-480.jpg",
          "sizeWebp": 35404,
          "sizeJpg": 41853
        },
        {
          "width": 960,
          "webp": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-hero-4x5-960.webp",
          "jpg": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-hero-4x5-960.jpg",
          "sizeWebp": 85046,
          "sizeJpg": 121586
        },
        {
          "width": 1600,
          "webp": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-hero-4x5-1600.webp",
          "jpg": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-hero-4x5-1600.jpg",
          "sizeWebp": 153140,
          "sizeJpg": 243381
        }
      ],
      "blurDataUrl": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQABAABIByJbACdAEQErQ3tzAA99/eRdn1cx2smWUJfNgAcMxVl4+oiBMeEaUhgY0ihCQg7VqDLurxjbIAAA=="
    },
    {
      "productSlug": "ambur-heritage-2in1-gift-box",
      "viewName": "unboxing-tan",
      "isMacro": false,
      "altText": "Luxury unboxing view of Ambur Tan leather goods enclosed in natural timber keepsake box",
      "squareImages": [
        {
          "width": 480,
          "webp": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-unboxing-tan-1x1-480.webp",
          "jpg": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-unboxing-tan-1x1-480.jpg",
          "sizeWebp": 23424,
          "sizeJpg": 29201
        },
        {
          "width": 960,
          "webp": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-unboxing-tan-1x1-960.webp",
          "jpg": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-unboxing-tan-1x1-960.jpg",
          "sizeWebp": 58372,
          "sizeJpg": 85385
        },
        {
          "width": 1600,
          "webp": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-unboxing-tan-1x1-1600.webp",
          "jpg": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-unboxing-tan-1x1-1600.jpg",
          "sizeWebp": 107954,
          "sizeJpg": 172490
        }
      ],
      "cardImages": [
        {
          "width": 480,
          "webp": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-unboxing-tan-4x5-480.webp",
          "jpg": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-unboxing-tan-4x5-480.jpg",
          "sizeWebp": 27948,
          "sizeJpg": 35553
        },
        {
          "width": 960,
          "webp": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-unboxing-tan-4x5-960.webp",
          "jpg": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-unboxing-tan-4x5-960.jpg",
          "sizeWebp": 65208,
          "sizeJpg": 97860
        },
        {
          "width": 1600,
          "webp": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-unboxing-tan-4x5-1600.webp",
          "jpg": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-unboxing-tan-4x5-1600.jpg",
          "sizeWebp": 121616,
          "sizeJpg": 190936
        }
      ],
      "blurDataUrl": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQABAABIByJbACdAD0oTzHnUAA/gnTkfjP8UlzXaoC6W+0NHDDcYYoRQxvTVj1ocvEA0JbY68YKuTBRU+XZG+Hc+XfcAAA"
    },
    {
      "productSlug": "ambur-heritage-2in1-gift-box",
      "viewName": "unboxing-black",
      "isMacro": false,
      "altText": "Midnight Onyx leather goods presented in custom magnetic-closure gift packaging",
      "squareImages": [
        {
          "width": 480,
          "webp": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-unboxing-black-1x1-480.webp",
          "jpg": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-unboxing-black-1x1-480.jpg",
          "sizeWebp": 26770,
          "sizeJpg": 32043
        },
        {
          "width": 960,
          "webp": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-unboxing-black-1x1-960.webp",
          "jpg": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-unboxing-black-1x1-960.jpg",
          "sizeWebp": 70894,
          "sizeJpg": 99321
        },
        {
          "width": 1600,
          "webp": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-unboxing-black-1x1-1600.webp",
          "jpg": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-unboxing-black-1x1-1600.jpg",
          "sizeWebp": 128002,
          "sizeJpg": 201962
        }
      ],
      "cardImages": [
        {
          "width": 480,
          "webp": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-unboxing-black-4x5-480.webp",
          "jpg": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-unboxing-black-4x5-480.jpg",
          "sizeWebp": 33076,
          "sizeJpg": 39857
        },
        {
          "width": 960,
          "webp": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-unboxing-black-4x5-960.webp",
          "jpg": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-unboxing-black-4x5-960.jpg",
          "sizeWebp": 77778,
          "sizeJpg": 115482
        },
        {
          "width": 1600,
          "webp": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-unboxing-black-4x5-1600.webp",
          "jpg": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-unboxing-black-4x5-1600.jpg",
          "sizeWebp": 140900,
          "sizeJpg": 225775
        }
      ],
      "blurDataUrl": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoQABAABIByJagCdAEVvCFOK2gAAMtPh34na6LTv0J9l7KKehOTMi9StMKx3XBkY4ibZIxfDHkp+V3xxrQTCuHerAAAAA=="
    },
    {
      "productSlug": "ambur-heritage-2in1-gift-box",
      "viewName": "macro-packaging",
      "isMacro": true,
      "altText": "Detail of artisan wooden keepsake gift box construction and premium leather corner finish",
      "squareImages": [
        {
          "width": 480,
          "webp": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-macro-packaging-1x1-480.webp",
          "jpg": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-macro-packaging-1x1-480.jpg",
          "sizeWebp": 17154,
          "sizeJpg": 23835
        },
        {
          "width": 960,
          "webp": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-macro-packaging-1x1-960.webp",
          "jpg": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-macro-packaging-1x1-960.jpg",
          "sizeWebp": 39204,
          "sizeJpg": 61686
        },
        {
          "width": 1600,
          "webp": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-macro-packaging-1x1-1600.webp",
          "jpg": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-macro-packaging-1x1-1600.jpg",
          "sizeWebp": 72874,
          "sizeJpg": 121341
        }
      ],
      "cardImages": [
        {
          "width": 480,
          "webp": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-macro-packaging-4x5-480.webp",
          "jpg": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-macro-packaging-4x5-480.jpg",
          "sizeWebp": 17894,
          "sizeJpg": 26139
        },
        {
          "width": 960,
          "webp": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-macro-packaging-4x5-960.webp",
          "jpg": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-macro-packaging-4x5-960.jpg",
          "sizeWebp": 41276,
          "sizeJpg": 67328
        },
        {
          "width": 1600,
          "webp": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-macro-packaging-4x5-1600.webp",
          "jpg": "/images/products/ambur-heritage-2in1-gift-box/ambur-heritage-2in1-gift-box-macro-packaging-4x5-1600.jpg",
          "sizeWebp": 75192,
          "sizeJpg": 130583
        }
      ],
      "blurDataUrl": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoQABAABIByJbACdAD0cw2awAD+6GmkRA3SfXOMXyco0vkIiYRZ3+D2qygy3vK4fG1bQVF9eeIQWYX/UllNRU3oAAA="
    }
  ]
};

/**
 * Returns gallery image angles ordered so that macro shots appear strictly LAST.
 */
export function getProductGalleryAssets(productSlug: string): ProductImageAsset[] {
  const assets = PRODUCT_IMAGE_REGISTRY[productSlug] || [];
  const regular = assets.filter((a) => !a.isMacro);
  const macro = assets.filter((a) => a.isMacro);
  return [...regular, ...macro];
}
