// Auto-generated by scripts/optimize-images.ts
// Sanitized for P0 Truth & Cleanup — strictly clean belt assets, no third-party branding.

export interface ProductImageAsset {
  productSlug: string;
  viewName: string;
  isMacro: boolean;
  altText: string;
  squareImages: {
    width: number;
    webp: string;
    jpg: string;
    sizeWebp: number;
    sizeJpg: number;
  }[];
  cardImages: {
    width: number;
    webp: string;
    jpg: string;
    sizeWebp: number;
    sizeJpg: number;
  }[];
  blurDataUrl: string;
}

export const PRODUCT_IMAGE_REGISTRY: Record<string, ProductImageAsset[]> = {
  "reversible-formal-casual-belt": [
    {
      productSlug: "reversible-formal-casual-belt",
      viewName: "hero",
      isMacro: false,
      altText: "Dino Leathers Ratchet Belt with brushed silver buckle in Jet Black coiled on travertine pedestal",
      squareImages: [
        {
          width: 480,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-1x1-480.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-1x1-480.jpg",
          sizeWebp: 28694,
          sizeJpg: 32069,
        },
        {
          width: 960,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-1x1-960.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-1x1-960.jpg",
          sizeWebp: 79440,
          sizeJpg: 99505,
        },
        {
          width: 1600,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-1x1-1600.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-1x1-1600.jpg",
          sizeWebp: 144602,
          sizeJpg: 213346,
        },
      ],
      cardImages: [
        {
          width: 480,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-4x5-480.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-4x5-480.jpg",
          sizeWebp: 31802,
          sizeJpg: 37222,
        },
        {
          width: 960,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-4x5-960.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-4x5-960.jpg",
          sizeWebp: 85840,
          sizeJpg: 113132,
        },
        {
          width: 1600,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-4x5-1600.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hero-4x5-1600.jpg",
          sizeWebp: 159134,
          sizeJpg: 240887,
        },
      ],
      blurDataUrl:
        "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAQCdASoQABAABIByJZACdADXCIg4GAAA/phA2JA6OiZPh21NyrHLVV232JI6fEPZvylEw8VxM1++qEJzDskjyW0Mzq/Vh2QXsoN59jjPd3RRO9+P0B/e1E/UnnGGRlYWBZ6gAAA=",
    },
    {
      productSlug: "reversible-formal-casual-belt",
      viewName: "angle-lifestyle",
      isMacro: false,
      altText: "Dino Leathers Belt in rich Ambur Cognac Tan bovine leather coiled on stone pedestal",
      squareImages: [
        {
          width: 480,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-1x1-480.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-1x1-480.jpg",
          sizeWebp: 30246,
          sizeJpg: 33720,
        },
        {
          width: 960,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-1x1-960.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-1x1-960.jpg",
          sizeWebp: 86072,
          sizeJpg: 106990,
        },
        {
          width: 1600,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-1x1-1600.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-1x1-1600.jpg",
          sizeWebp: 158762,
          sizeJpg: 229727,
        },
      ],
      cardImages: [
        {
          width: 480,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-4x5-480.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-4x5-480.jpg",
          sizeWebp: 34596,
          sizeJpg: 39365,
        },
        {
          width: 960,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-4x5-960.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-4x5-960.jpg",
          sizeWebp: 95052,
          sizeJpg: 121490,
        },
        {
          width: 1600,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-4x5-1600.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-angle-lifestyle-4x5-1600.jpg",
          sizeWebp: 173466,
          sizeJpg: 260940,
        },
      ],
      blurDataUrl:
        "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADwAQCdASoQABAABIByJbACdADNDhUPwsgA/pgNZIKzrcU9F7HNGit9s/AUUY4Japw3edKeGjv1KfL4AONupWJu1mtK3/dXLz9o+uEKGFEaCYPN4Ywc39QE1N7lopFFXq9GZwAA",
    },
    {
      productSlug: "reversible-formal-casual-belt",
      viewName: "hardware-mechanism",
      isMacro: false,
      altText: "Close-up of 32-notch ratchet track mechanism and quick-release lever",
      squareImages: [
        {
          width: 480,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-1x1-480.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-1x1-480.jpg",
          sizeWebp: 39858,
          sizeJpg: 41895,
        },
        {
          width: 960,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-1x1-960.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-1x1-960.jpg",
          sizeWebp: 116548,
          sizeJpg: 131276,
        },
        {
          width: 1600,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-1x1-1600.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-1x1-1600.jpg",
          sizeWebp: 202178,
          sizeJpg: 270851,
        },
      ],
      cardImages: [
        {
          width: 480,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-4x5-480.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-4x5-480.jpg",
          sizeWebp: 47190,
          sizeJpg: 50064,
        },
        {
          width: 960,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-4x5-960.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-4x5-960.jpg",
          sizeWebp: 121538,
          sizeJpg: 148883,
        },
        {
          width: 1600,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-4x5-1600.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-hardware-mechanism-4x5-1600.jpg",
          sizeWebp: 217984,
          sizeJpg: 306491,
        },
      ],
      blurDataUrl:
        "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQAQCdASoQABAABIByJZACdADP35KgAAD9/KeNqCnCTSLEeUaN0E/BB58etCwyPGbMXD3ta8gHx/hVp5+JO6xpWWPrNA/l+YoAHDBQFVwcZ7fKesJW/17PGwqAbLG0UHyfpdYUgAA=",
    },
    {
      productSlug: "reversible-formal-casual-belt",
      viewName: "worn-lifestyle",
      isMacro: false,
      altText: "Dino Leathers belt styled on formal trousers and collared shirt",
      squareImages: [
        {
          width: 480,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-1x1-480.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-1x1-480.jpg",
          sizeWebp: 21900,
          sizeJpg: 28281,
        },
        {
          width: 960,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-1x1-960.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-1x1-960.jpg",
          sizeWebp: 63816,
          sizeJpg: 88067,
        },
        {
          width: 1600,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-1x1-1600.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-1x1-1600.jpg",
          sizeWebp: 127942,
          sizeJpg: 196606,
        },
      ],
      cardImages: [
        {
          width: 480,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-4x5-480.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-4x5-480.jpg",
          sizeWebp: 24450,
          sizeJpg: 32611,
        },
        {
          width: 960,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-4x5-960.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-4x5-960.jpg",
          sizeWebp: 73906,
          sizeJpg: 103010,
        },
        {
          width: 1600,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-4x5-1600.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-worn-lifestyle-4x5-1600.jpg",
          sizeWebp: 148114,
          sizeJpg: 231448,
        },
      ],
      blurDataUrl:
        "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoQABAABIByJYwAAhY8+rO1AAD+188Po6EqXo3ilOXqI6yu+qsloyOEBYek08/hCu2RwBUNVdg0ZeG7jAPrQU/1hJkbfpiVO+DHkivKtvKPIAAA",
    },
    {
      productSlug: "reversible-formal-casual-belt",
      viewName: "macro-grain",
      isMacro: true,
      altText: "Macro texture of brushed alloy buckle and Ambur bovine leather",
      squareImages: [
        {
          width: 480,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-1x1-480.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-1x1-480.jpg",
          sizeWebp: 34580,
          sizeJpg: 35913,
        },
        {
          width: 960,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-1x1-960.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-1x1-960.jpg",
          sizeWebp: 104462,
          sizeJpg: 115415,
        },
        {
          width: 1600,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-1x1-1600.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-1x1-1600.jpg",
          sizeWebp: 184188,
          sizeJpg: 240984,
        },
      ],
      cardImages: [
        {
          width: 480,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-4x5-480.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-4x5-480.jpg",
          sizeWebp: 43020,
          sizeJpg: 43676,
        },
        {
          width: 960,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-4x5-960.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-4x5-960.jpg",
          sizeWebp: 115164,
          sizeJpg: 133658,
        },
        {
          width: 1600,
          webp: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-4x5-1600.webp",
          jpg: "/images/products/reversible-formal-casual-belt/reversible-formal-casual-belt-macro-grain-4x5-1600.jpg",
          sizeWebp: 205642,
          sizeJpg: 279224,
        },
      ],
      blurDataUrl:
        "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQAgCdASoQABAABIByJQBOgBmEpGmhN2+AAP5kubzqUVWP3h8wUDEGI6dB45QHzNUyzAY4f3DUIJIgAQyTJQ+SYVoQ60MX0qE+cyAJMIrm9czcn40FQF3g84nSE4z3XeOTgAAA",
    },
  ],
};

export function getProductGalleryAssets(slug: string): ProductImageAsset[] {
  return PRODUCT_IMAGE_REGISTRY[slug] || [];
}